AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0323c3dd2da7fb37d
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  Instance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
      IamInstanceProfile: !Ref IamInstanceProfile
      UserData:
        Fn::Base64: !Sub
        - |
          #!/bin/bash
          yum update -y
          yum install -y fuse
          curl -L https://github.com/kahing/goofys/releases/latest/download/goofys -o /usr/local/bin/goofys
          chmod +x /usr/local/bin/goofys
          mkdir /mnt/s3
          goofys ${Bucket} /mnt/s3 -o allow_other,--uid=$(id -u),--gid=$(id -g)
        - Bucket: !Ref S3Bucket
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - !Ref InstanceRole
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole    
      Description: Allows EC2 instances to call AWS services on your behalf.
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  SessionManagerUrl:
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/systems-manager/session-manager/${Instance}
